sudo: required
services:
    - docker

script:
    - docker run -v $PWD:/jade blockstream/verde@sha256:8ce8fa4ee3d2f795e8ade65fe31487729624e574e7f1c1b408eb89147215131f /bin/bash -c "cd /jade && ./format.sh && git diff --exit-code && . $HOME/esp/esp-idf/export.sh && cp configs/sdkconfig_display.defaults sdkconfig.defaults && idf.py all size-components size"
