sudo: required
services:
    - docker

script:
    - docker run -v $PWD:/jade blockstream/verde@sha256:2578469780f69b52b55f63fdbe622eecf738b5fbe2068121888c2b898bc84b2b /bin/bash -c "cd /jade && ./format.sh && git diff --exit-code && . $HOME/esp/esp-idf/export.sh && cp configs/sdkconfig_display.defaults sdkconfig.defaults && idf.py all size-components size"
